spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    password: root
    username: root
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 2000
    restart:
      enabled: true #是否支持热部署
      exclude: static/**,templates/**
      include:
        mapper: /mapper-[\\w-\\.]+jar
  　　  pagehelper: /pagehelper-[\\w-\\.]+jar
