# mgr config
server:
  port: 8080
  maxHttpHeaderSize: 102400000
  maxHttpPostSize: 102400000
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
    maxHttpHeaderSize: 102400000
    maxHttpPostSize: 102400000

business:
  tenant-id: a1

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver  #com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
#  mapper-locations: classpath:com/iee/orm/mybatis/mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO

logging:
  level:
    root: debug #warn
    # 打印sql的log
    com.iee.orm.mybatis: debug
    org.springframework.web: debug

local:
  uploadFilesFolder: f://lmwy/upload/
