spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
  session:
    store-type: none


javasea:
  security:
    browser:
#      signInPage: /demo-signIn.html   # 可以自定义登陆页面，默认是javasea-rbac-security-browser项目下的imooc-signIn.html
      signInResponseType: JSON   #JSON 或者 REDIRECT，默认是 JSON
    code:
      image:
        length: 4                    #自定义图片验证码长度，默认是4
        width: 50                   #图片验证码宽度，默认是67
        height: 30                   #图片验证码高度， 默认是23
        expireIn: 30                 #图片验证码过期时间，单位秒，默认是60秒
        url: /user,/user/*           #添加自定义拦截的url，默认已经添加登陆请求的拦截，支持ant模式，配置后，访问该url会进行验证码校验，如果验证不通过则不可访问
      sms:
        length: 6                    #自定义短信验证码长度，默认是6
        expireIn: 60                 #自定义验证码过期时间，默认是60秒
        url: /user,/user/*
